<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        DB::table('products')->delete();
        
        DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 1,
                'product_category_id' => 1,
                'code' => '001',
                'wp_code' => '1',
                'name' => 'Savon très doux',
                'launch_date' => '2011-03-21',
                'net_weight' => 100.0,
                'ean_code' => '1234567891234',
                'description' => NULL,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2021-01-29 04:25:10',
                'updated_at' => '2024-02-18 17:36:51',
            ),
            1 => 
            array (
                'id' => 2,
                'product_category_id' => 1,
                'code' => '002',
                'wp_code' => '2',
                'name' => 'Savon nature',
                'launch_date' => '2021-01-29',
                'net_weight' => 100.0,
                'ean_code' => '1234567894561236',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-01-29 04:25:55',
                'updated_at' => '2021-01-29 04:25:55',
            ),
            2 => 
            array (
                'id' => 3,
                'product_category_id' => 1,
                'code' => '003',
                'wp_code' => '12',
                'name' => 'Savon d\'Alep 15%',
                'launch_date' => '2015-01-01',
                'net_weight' => 100.0,
                'ean_code' => '12',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-01-29 04:26:52',
                'updated_at' => '2021-01-29 04:27:01',
            ),
            3 => 
            array (
                'id' => 4,
                'product_category_id' => 1,
                'code' => '004',
                'wp_code' => '12',
                'name' => 'Savon curcuma',
                'launch_date' => '2021-01-12',
                'net_weight' => 100.0,
                'ean_code' => '12',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-01-29 04:28:08',
                'updated_at' => '2021-01-29 04:29:18',
            ),
            4 => 
            array (
                'id' => 5,
                'product_category_id' => 1,
                'code' => '005',
                'wp_code' => '12',
                'name' => 'Savon Rhassoul',
                'launch_date' => '2014-01-01',
                'net_weight' => 100.0,
                'ean_code' => '12',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-01-29 04:29:13',
                'updated_at' => '2021-01-29 04:29:13',
            ),
            5 => 
            array (
                'id' => 6,
                'product_category_id' => 1,
                'code' => '006',
                'wp_code' => '12',
                'name' => 'Savon Le Sensuel',
                'launch_date' => '2011-03-21',
                'net_weight' => 100.0,
                'ean_code' => '12',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-01-29 04:30:17',
                'updated_at' => '2021-01-29 04:30:17',
            ),
            6 => 
            array (
                'id' => 7,
                'product_category_id' => 1,
                'code' => '007',
                'wp_code' => '12',
                'name' => 'Savon Le Tonique',
                'launch_date' => '2021-01-29',
                'net_weight' => 100.0,
                'ean_code' => '12',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-01-29 04:30:48',
                'updated_at' => '2021-01-29 04:30:48',
            ),
            7 => 
            array (
                'id' => 8,
                'product_category_id' => 1,
                'code' => '008',
                'wp_code' => '12',
                'name' => 'Savon Le Soyeux',
                'launch_date' => '2011-03-21',
                'net_weight' => 100.0,
                'ean_code' => '12',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-01-29 04:31:27',
                'updated_at' => '2021-01-29 04:31:27',
            ),
            8 => 
            array (
                'id' => 9,
                'product_category_id' => 1,
                'code' => '009',
                'wp_code' => '12',
                'name' => 'Savon Le Colosse',
                'launch_date' => '2021-01-29',
                'net_weight' => 100.0,
                'ean_code' => '12',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-01-29 04:32:30',
                'updated_at' => '2021-01-29 04:32:30',
            ),
            9 => 
            array (
                'id' => 10,
                'product_category_id' => 1,
                'code' => '010',
                'wp_code' => '12',
                'name' => 'Savon l\'Enthousiaste',
                'launch_date' => '2011-03-21',
                'net_weight' => 100.0,
                'ean_code' => '12',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-01-29 04:33:39',
                'updated_at' => '2021-01-29 04:33:39',
            ),
            10 => 
            array (
                'id' => 11,
                'product_category_id' => 1,
                'code' => '011',
                'wp_code' => '12',
                'name' => 'Savon l\'Intuitif',
                'launch_date' => '2011-03-21',
                'net_weight' => 100.0,
                'ean_code' => '12',
                'description' => NULL,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2021-01-29 04:34:37',
                'updated_at' => '2024-02-18 17:42:00',
            ),
            11 => 
            array (
                'id' => 12,
                'product_category_id' => 1,
                'code' => '012',
                'wp_code' => '12',
                'name' => 'Savon le Gourmand',
                'launch_date' => '2021-01-29',
                'net_weight' => 100.0,
                'ean_code' => '12',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-01-29 04:35:37',
                'updated_at' => '2021-01-29 04:35:37',
            ),
            12 => 
            array (
                'id' => 13,
                'product_category_id' => 1,
                'code' => '013',
                'wp_code' => '12',
                'name' => 'Savon l\'Evident',
                'launch_date' => '2011-03-21',
                'net_weight' => 100.0,
                'ean_code' => '12',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-01-29 04:36:09',
                'updated_at' => '2021-01-29 04:36:09',
            ),
            13 => 
            array (
                'id' => 14,
                'product_category_id' => 1,
                'code' => '014',
                'wp_code' => '12',
                'name' => 'Savon Très Doux',
                'launch_date' => '2016-01-01',
                'net_weight' => 170.0,
                'ean_code' => '12',
                'description' => NULL,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2021-01-29 04:37:25',
                'updated_at' => '2024-02-18 17:37:08',
            ),
            14 => 
            array (
                'id' => 15,
                'product_category_id' => 1,
                'code' => '015',
                'wp_code' => '12',
                'name' => 'Savon',
                'launch_date' => '2021-01-29',
                'net_weight' => 100.0,
                'ean_code' => '12',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-01-29 04:39:27',
                'updated_at' => '2021-01-29 04:39:27',
            ),
            15 => 
            array (
                'id' => 16,
                'product_category_id' => 1,
                'code' => '016',
                'wp_code' => '12',
                'name' => 'Savon d\'Alep 15%',
                'launch_date' => '2021-01-29',
                'net_weight' => 170.0,
                'ean_code' => '12',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-01-29 04:40:03',
                'updated_at' => '2021-01-29 04:40:20',
            ),
            16 => 
            array (
                'id' => 17,
                'product_category_id' => 1,
                'code' => '017',
                'wp_code' => '12',
                'name' => 'Savon Curcuma',
                'launch_date' => '2016-01-01',
                'net_weight' => 170.0,
                'ean_code' => '12',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-01-29 04:41:15',
                'updated_at' => '2021-01-29 04:47:39',
            ),
            17 => 
            array (
                'id' => 18,
                'product_category_id' => 1,
                'code' => '018',
                'wp_code' => '21',
                'name' => 'Savon Rhassoul',
                'launch_date' => '2016-01-01',
                'net_weight' => 170.0,
                'ean_code' => '12',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-01-29 04:47:23',
                'updated_at' => '2021-01-29 04:47:23',
            ),
            18 => 
            array (
                'id' => 19,
                'product_category_id' => 1,
                'code' => '019',
                'wp_code' => '12',
                'name' => 'Savon l\'Intuitif',
                'launch_date' => '2020-07-01',
                'net_weight' => 170.0,
                'ean_code' => '12',
                'description' => NULL,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2021-01-29 04:48:32',
                'updated_at' => '2024-02-18 17:42:17',
            ),
            19 => 
            array (
                'id' => 20,
                'product_category_id' => 1,
                'code' => '020',
                'wp_code' => '12',
                'name' => 'Savon l\'Enthousiaste',
                'launch_date' => '2021-01-16',
                'net_weight' => 170.0,
                'ean_code' => '12',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-01-29 04:49:47',
                'updated_at' => '2021-01-29 04:49:47',
            ),
            20 => 
            array (
                'id' => 21,
                'product_category_id' => 1,
                'code' => '021',
                'wp_code' => '12',
                'name' => 'Savon le Sensuel',
                'launch_date' => '2021-07-01',
                'net_weight' => 170.0,
                'ean_code' => '12',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-01-29 04:50:30',
                'updated_at' => '2021-01-29 04:50:30',
            ),
            21 => 
            array (
                'id' => 22,
                'product_category_id' => 1,
                'code' => '022',
                'wp_code' => '12',
                'name' => 'Savon le Closse',
                'launch_date' => '2020-07-01',
                'net_weight' => 170.0,
                'ean_code' => '12',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-01-29 04:51:30',
                'updated_at' => '2021-01-29 04:51:30',
            ),
            22 => 
            array (
                'id' => 23,
                'product_category_id' => 1,
                'code' => '030',
                'wp_code' => '12',
                'name' => 'Savon de Marseille Type 1',
                'launch_date' => '2018-07-01',
                'net_weight' => 100.0,
                'ean_code' => '12',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-01-29 04:52:45',
                'updated_at' => '2021-01-29 04:53:23',
            ),
            23 => 
            array (
                'id' => 24,
                'product_category_id' => 1,
                'code' => '031',
                'wp_code' => '12',
                'name' => 'Savon de Marseille Type 1',
                'launch_date' => '2020-07-01',
                'net_weight' => 250.0,
                'ean_code' => '12',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-01-29 04:53:13',
                'updated_at' => '2021-01-29 04:55:46',
            ),
            24 => 
            array (
                'id' => 25,
                'product_category_id' => 1,
                'code' => '032',
                'wp_code' => '12',
                'name' => 'Savon de Marseille Type 2',
                'launch_date' => '2018-07-01',
                'net_weight' => 100.0,
                'ean_code' => '12',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-01-29 04:55:38',
                'updated_at' => '2021-01-29 05:00:11',
            ),
            25 => 
            array (
                'id' => 26,
                'product_category_id' => 1,
                'code' => '033',
                'wp_code' => '12',
                'name' => 'Savon de Marseille Type 2',
                'launch_date' => '2021-01-29',
                'net_weight' => 250.0,
                'ean_code' => '12',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-01-29 04:56:28',
                'updated_at' => '2021-01-29 04:56:28',
            ),
            26 => 
            array (
                'id' => 27,
                'product_category_id' => 1,
                'code' => '034',
                'wp_code' => '12',
                'name' => 'Savon de Marseille Type 3',
                'launch_date' => '2021-01-29',
                'net_weight' => 100.0,
                'ean_code' => '12',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-01-29 04:59:19',
                'updated_at' => '2021-01-29 05:00:03',
            ),
            27 => 
            array (
                'id' => 28,
                'product_category_id' => 1,
                'code' => '035',
                'wp_code' => '12',
                'name' => 'Savon de Marseille Type 3',
                'launch_date' => '2021-01-29',
                'net_weight' => 250.0,
                'ean_code' => '12',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-01-29 04:59:55',
                'updated_at' => '2021-01-29 04:59:55',
            ),
            28 => 
            array (
                'id' => 29,
                'product_category_id' => 1,
                'code' => '040',
                'wp_code' => '12',
                'name' => 'Savon de Goa Mains',
                'launch_date' => '2020-09-01',
                'net_weight' => 150.0,
                'ean_code' => '12',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-01-29 05:02:36',
                'updated_at' => '2021-01-29 05:02:36',
            ),
            29 => 
            array (
                'id' => 30,
                'product_category_id' => 1,
                'code' => '041',
                'wp_code' => '12',
                'name' => 'Savon de Goa Purifiant',
                'launch_date' => '2021-01-29',
                'net_weight' => 150.0,
                'ean_code' => '12',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-01-29 05:03:07',
                'updated_at' => '2021-01-29 05:03:07',
            ),
            30 => 
            array (
                'id' => 31,
                'product_category_id' => 1,
                'code' => '042',
                'wp_code' => '12',
                'name' => 'Savon de Goa Peaux Sensibles',
                'launch_date' => '2017-01-01',
                'net_weight' => 150.0,
                'ean_code' => '12',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-01-29 05:04:48',
                'updated_at' => '2021-01-29 05:05:01',
            ),
            31 => 
            array (
                'id' => 32,
                'product_category_id' => 1,
                'code' => '043',
                'wp_code' => '232',
                'name' => 'Savon de Goa exfoliant',
                'launch_date' => '2021-06-21',
                'net_weight' => 150.0,
                'ean_code' => '1234543223',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-06-21 15:56:22',
                'updated_at' => '2021-06-21 16:24:18',
            ),
            32 => 
            array (
                'id' => 33,
                'product_category_id' => 1,
                'code' => '044',
                'wp_code' => '1234',
                'name' => 'Savon de Goa Freedom',
                'launch_date' => '2021-06-21',
                'net_weight' => 150.0,
                'ean_code' => '1234',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-06-21 16:07:47',
                'updated_at' => '2021-06-21 16:07:47',
            ),
            33 => 
            array (
                'id' => 34,
                'product_category_id' => 1,
                'code' => '028',
                'wp_code' => 'HUIL12',
                'name' => 'Savon purifiant',
                'launch_date' => '2021-03-01',
                'net_weight' => 120.0,
                'ean_code' => '1234567891',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-06-21 16:19:34',
                'updated_at' => '2021-06-21 16:19:34',
            ),
            34 => 
            array (
                'id' => 35,
                'product_category_id' => 1,
                'code' => '029',
                'wp_code' => 'XX',
                'name' => 'Savon extra doux',
                'launch_date' => '2020-06-01',
                'net_weight' => 120.0,
                'ean_code' => '123456789',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-06-21 16:24:03',
                'updated_at' => '2021-06-21 16:24:03',
            ),
            35 => 
            array (
                'id' => 36,
                'product_category_id' => 7,
                'code' => '080',
                'wp_code' => '12',
                'name' => 'Shampoing solide',
                'launch_date' => '2019-09-01',
                'net_weight' => 120.0,
                'ean_code' => '123456789',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-06-21 16:30:47',
                'updated_at' => '2021-06-21 16:31:02',
            ),
            36 => 
            array (
                'id' => 37,
                'product_category_id' => 11,
                'code' => '090',
                'wp_code' => '1235',
                'name' => 'Dentifrice solide',
                'launch_date' => '2021-06-21',
                'net_weight' => 30.0,
                'ean_code' => '1234',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-06-21 16:37:41',
                'updated_at' => '2021-06-21 16:37:41',
            ),
            37 => 
            array (
                'id' => 38,
                'product_category_id' => 2,
                'code' => '100',
                'wp_code' => '12313',
                'name' => 'Baume qui soulage',
                'launch_date' => '2021-06-21',
                'net_weight' => 50.0,
                'ean_code' => '3770002301203',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-06-21 16:39:22',
                'updated_at' => '2021-06-21 16:39:22',
            ),
            38 => 
            array (
                'id' => 39,
                'product_category_id' => 2,
                'code' => '101',
                'wp_code' => '1231',
                'name' => 'Baume universel',
                'launch_date' => '2018-06-01',
                'net_weight' => 50.0,
                'ean_code' => '3770002301401',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-06-21 16:40:59',
                'updated_at' => '2021-06-21 16:40:59',
            ),
            39 => 
            array (
                'id' => 40,
                'product_category_id' => 3,
                'code' => '102',
                'wp_code' => '12',
                'name' => 'Baume déodorant fraîcheur',
                'launch_date' => '2018-03-01',
                'net_weight' => 50.0,
                'ean_code' => '1234456667',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-06-21 16:42:57',
                'updated_at' => '2021-06-21 16:42:57',
            ),
            40 => 
            array (
                'id' => 41,
                'product_category_id' => 3,
                'code' => '103',
                'wp_code' => '123',
                'name' => 'Baume dédorant une absolue tendresse',
                'launch_date' => '2018-06-01',
                'net_weight' => 50.0,
                'ean_code' => '3770002301395',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-06-21 16:46:05',
                'updated_at' => '2021-06-21 16:52:00',
            ),
            41 => 
            array (
                'id' => 42,
                'product_category_id' => 3,
                'code' => '104',
                'wp_code' => '123',
                'name' => 'Baume déodorant une absolue douceur',
                'launch_date' => '2021-06-21',
                'net_weight' => 50.0,
                'ean_code' => '3770002301371',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-06-21 16:47:23',
                'updated_at' => '2021-06-21 16:52:38',
            ),
            42 => 
            array (
                'id' => 43,
                'product_category_id' => 1,
                'code' => '060',
                'wp_code' => 'x',
                'name' => 'Savon tilleul',
                'launch_date' => '2021-07-01',
                'net_weight' => 150.0,
                'ean_code' => 'x',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-06-21 16:58:35',
                'updated_at' => '2021-06-21 16:59:46',
            ),
            43 => 
            array (
                'id' => 44,
                'product_category_id' => 1,
                'code' => '061',
                'wp_code' => 'x',
                'name' => 'Savon tilleul visage',
                'launch_date' => '2021-07-01',
                'net_weight' => 100.0,
                'ean_code' => 'x',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-06-21 16:59:31',
                'updated_at' => '2021-06-21 16:59:31',
            ),
            44 => 
            array (
                'id' => 45,
                'product_category_id' => 7,
                'code' => '062',
                'wp_code' => 'x',
                'name' => 'Shampoing solide tilleul',
                'launch_date' => '2021-06-21',
                'net_weight' => 120.0,
                'ean_code' => 'x',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-06-21 17:00:52',
                'updated_at' => '2021-06-21 17:00:52',
            ),
            45 => 
            array (
                'id' => 46,
                'product_category_id' => 2,
                'code' => '065',
                'wp_code' => 'x',
                'name' => 'Baume tilleul',
                'launch_date' => '2021-07-01',
                'net_weight' => 50.0,
                'ean_code' => 'x',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-06-21 17:02:43',
                'updated_at' => '2021-06-21 17:04:10',
            ),
            46 => 
            array (
                'id' => 47,
                'product_category_id' => 3,
                'code' => '064',
                'wp_code' => 'c',
                'name' => 'Baume déodorant tilleul',
                'launch_date' => '2021-06-21',
                'net_weight' => 50.0,
                'ean_code' => 'c',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-06-21 17:03:39',
                'updated_at' => '2021-06-21 17:03:39',
            ),
            47 => 
            array (
                'id' => 48,
                'product_category_id' => 1,
                'code' => '063',
                'wp_code' => 'x',
                'name' => 'Savon liquide tilleul',
                'launch_date' => '2021-06-21',
                'net_weight' => 500.0,
                'ean_code' => 'x',
                'description' => NULL,
                'is_active' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-06-21 17:04:59',
                'updated_at' => '2021-06-21 17:04:59',
            ),
        ));
        
        
    }
}